#!/bin/sh
set -e

dot_dir=$1
png_dir=$2

gen_fws() {
    tier=$1
    qt=$2
    if [ -n "$qt" ] ; then
        opts=--qt
    else
        opts=""
    fi

    for fw_dir in $dot_dir/$tier/*/ ; do
        fw=$(basename $fw_dir)
        png=$png_dir/$tier-$fw.png
        echo $png
        ./kf5dot-generate $dot_dir/tier*/*/*.dot --framework $fw $opts | dot -Tpng > $png
    done
}

mkdir -p $png_dir

gen_fws tier1 1
gen_fws tier2 1
gen_fws tier3
gen_fws tier4

echo "kf5.png"
./kf5dot-generate $dot_dir/tier*/*/*.dot | tred | dot -Tpng > $png_dir/kf5.png
