#!/usr/bin/env python
# encoding: utf-8
import argparse
import itertools
import fnmatch
import os
import re
import shutil
import sys
import tempfile

import yapgvb

from block import Block

DESCRIPTION = """\
"""

ROOT_NODE_ATTRS = dict(fontsize=12, shape="box")

TIER_ATTRS = dict(style="filled", fillcolor="azure")

OTHER_ATTRS = dict(style="filled", fillcolor="cornsilk")

QT_ATTRS = dict(style="filled", fillcolor="darkseagreen1")

FW_ATTRS = dict(style="filled", fillcolor="paleturquoise")

TARGET_SHAPES = ["polygon", "house"]

DEPS_SHAPE = "ellipse"

DEPS_BLACKLIST = ["-l*", "/*", "m", "pthread", "util", "nsl", "*example*", "*demo*", "*test*", "*Test*"]

def preprocess(fname):
    lst = []
    gfx = yapgvb.Graph().read(fname)
    txt = open(fname).read()
    targets = []
    for node in gfx.nodes:
        label = node.label.replace("KF5::", "")
        if node.shape in TARGET_SHAPES:
            targets.append(label)
        txt = txt.replace('"' + node.name + '"', '"' + label + '"')

    # Sometimes cmake will generate an entry for the target alias, something
    # like this:
    #
    # "node9" [ label="KParts" shape="polygon"];
    # ...
    # "node15" [ label="KF5::KParts" shape="ellipse"];
    # ...
    #
    # After our node renaming, this ends up with a second "KParts" node
    # definition, which we need to get rid of.
    for target in targets:
        rx = r' *"' + target + '".*label="KF5::' + target + '".*shape="ellipse".*;'
        txt = re.sub(rx, '', txt)
    return txt


def to_temp_file(dirname, fname, content):
    tier = fname.split("/")[-3]
    path = os.path.join(dirname, tier + "-" + os.path.basename(fname))
    if os.path.exists(path):
        raise Exception("{} already exists".format(path))
    open(path, "w").write(content)
    return path


class Framework(object):
    def __init__(self, fname, options):
        self.options = options

        lst = os.path.basename(fname).split("-")
        self.tier = lst[0]
        self.name = lst[1].replace(".dot", "")

        # Target names
        self.targets = set([])

        # lists of (tail, head) tuples
        self.edges = []

        src = yapgvb.Graph().read(fname)

        for node in src.nodes:
            if node.shape in TARGET_SHAPES and self.want(node):
                self.targets.add(node.name)
        for edge in src.edges:
            if self.want(edge.head) and self.want(edge.tail):
                self.edges.append((edge.tail.name, edge.head.name))

    def want(self, node):
        if node.shape not in TARGET_SHAPES and node.shape != DEPS_SHAPE:
            return False
        name = node.name

        for pattern in DEPS_BLACKLIST:
            if fnmatch.fnmatchcase(node.name, pattern):
                return False
        if not self.options.qt and name.startswith("Qt"):
            return False
        return True

    def __repr__(self):
        return self.name


def find_not_target_nodes(frameworks):
    nodes = set([])
    targets = set([])
    for fw in frameworks:
        targets.update(fw.targets)
        nodes.update([x[1] for x in fw.edges])
    return nodes.difference(targets)


class FrameworkCmp(object):
    def __init__(self, frameworks):
        self.fw_for_target = {}
        for fw in frameworks:
            for target in fw.targets:
                self.fw_for_target[target] = fw
        self.src = set(frameworks)
        self.dst = []

    def __call__(self, fw1, fw2):
        if self.depends_on(fw1, fw2):
            return 1
        if self.depends_on(fw2, fw1):
            return -1
        return 0

    def depends_on(self, depender_fw, provider_fw):
        for edge in depender_fw.edges:
            dep_target = edge[1]
            if dep_target in provider_fw.targets:
                return True

            try:
                dep_fw = self.fw_for_target[dep_target]
            except KeyError:
                # No framework for this target, must be an external dependency,
                # carry on
                continue
            if dep_fw != depender_fw and self.depends_on(dep_fw, provider_fw):
                return True

        return False


class DotWriter(Block):
    def __init__(self, frameworks, out):
        Block.__init__(self, out)
        self.frameworks = frameworks

    def write(self):
        with self.curly_block("digraph Root") as root:
            root.write_list_attrs("node", **ROOT_NODE_ATTRS)

            other_nodes = find_not_target_nodes(self.frameworks)
            qt_nodes = set([x for x in other_nodes if x.startswith("Qt")])
            other_nodes.difference_update(qt_nodes)

            if qt_nodes:
                with root.cluster_block("Qt", **QT_ATTRS) as b:
                    b.write_nodes(qt_nodes)

            if other_nodes:
                with root.cluster_block("Others", **OTHER_ATTRS) as b:
                    b.write_nodes(other_nodes)

            for tier, frameworks in itertools.groupby(self.frameworks, lambda x: x.tier):
                with root.cluster_block(tier, **TIER_ATTRS) as tier_block:
                    # Sort frameworks within the tier to ensure frameworks which
                    # depend on other frameworks from that tier are listed after
                    # their dependees.
                    frameworks = list(frameworks)
                    for fw in sorted(frameworks, cmp=FrameworkCmp(frameworks)):
                        self.write_framework(tier_block, fw)

    def write_framework(self, tier_block, fw):
        with tier_block.cluster_block(fw.name, **FW_ATTRS) as fw_block:
            fw_block.write_nodes(fw.targets)
            for edge in sorted(fw.edges, key=lambda x:x[1]):
                fw_block.writeln('"{}" -> "{}";'.format(edge[0], edge[1]))


def find_framework_by_name(frameworks, name):
    for fw in frameworks:
        if fw.name == name:
            return fw
    return None


def remove_unused_frameworks(frameworks, wanted_fw):
    def has_dependees(lst, target_fw):
        for fw in lst:
            if fw == target_fw:
                continue
            for edge in fw.edges:
                if edge[1] in target_fw.targets:
                    return True
        return False

    done = False
    old_lst = frameworks
    while not done:
        lst = []
        done = True
        for fw in old_lst:
            if fw == wanted_fw:
                lst.append(fw)
                continue
            if has_dependees(old_lst, fw):
                lst.append(fw)
            else:
                done = False
        old_lst = lst
    return lst


def main():
    parser = argparse.ArgumentParser(description=DESCRIPTION)

    parser.add_argument("-o", "--output", dest="output", default="-",
        help="Output to FILE", metavar="FILE")

    parser.add_argument("--qt", dest="qt", action="store_true",
        help="Show Qt libraries")

    parser.add_argument("--framework", dest="framework",
        help="Only show dependencies of framework FRAMEWORK", metavar="FRAMEWORK")

    parser.add_argument("dot_files", nargs="+")

    args = parser.parse_args()

    tmpdir = tempfile.mkdtemp(prefix="kf5dot")
    try:
        input_files = [to_temp_file(tmpdir, x, preprocess(x)) for x in args.dot_files]
        frameworks = [Framework(x, args) for x in input_files]
    finally:
        shutil.rmtree(tmpdir)

    if args.output == "-":
        out = sys.stdout
    else:
        out = open(args.output, "w")

    if args.framework:
        wanted_fw = find_framework_by_name(frameworks, args.framework)
        if wanted_fw is None:
            sys.stderr.write("No framework named {}.\n".format(args.framework))
            return 1
        frameworks = remove_unused_frameworks(frameworks, wanted_fw)

    writer = DotWriter(frameworks, out)
    writer.write()

    return 0


if __name__ == "__main__":
    sys.exit(main())
# vi: ts=4 sw=4 et
