#!/bin/sh
set -e

usage() {
    cat <<EOF
Usage: $(basename $0) <frameworks-dir> <dot-dest-dir>

Generate Graphviz dot files for all frameworks within kdelibs-dir.

Dot files are generated in dot-dest-dir, which will be created if it does not
exist.

EOF
exit 1
}

if [ $# -ne 2 ] ; then
    usage
fi

old_pwd=$PWD
cd $1
fw_base_dir=$PWD
cd $old_pwd

dst_dir=$2

for fw_dir in $fw_base_dir/*/ ; do
    if [ ! -e $fw_dir/CMakeLists.txt ] ; then
        continue
    fi
    fw=$(basename $fw_dir)
    tier=$(awk -F: '$1 == "tier" { print $2}' $fw_dir/$fw.yaml | sed 's/ //')

    echo "$tier $fw_dir"
    build_dir=$dst_dir/tier$tier/$fw
    mkdir -p $build_dir
    ( cd $build_dir ; cmake $fw_dir --graphviz=$fw.dot > /dev/null )
done
