#! /usr/bin/env python3
# -*- coding: utf-8 -*-
#
# SPDX-FileCopyrightText: 2014 Alex Merry <alex.merry@kdemail.net>
# SPDX-FileCopyrightText: 2014 Aurélien Gâteau <agateau@kde.org>
# SPDX-FileCopyrightText: 2014 Alex Turbov <i.zaufi@gmail.com>
# SPDX-FileCopyrightText: 2016 Olivier Churlaud <olivier@churlaud.com>
#
# SPDX-License-Identifier: BSD-2-Clause

import logging
import codecs
import os
import sys
import time
import datetime

from kapidox import generator, utils, argparserutils, preprocessing, hlfunctions

try:
    from kapidox import depdiagram
    DEPDIAGRAM_AVAILABLE = True
except ImportError:
    DEPDIAGRAM_AVAILABLE = False


def get_identities():
    """Download the "accounts" file on the KDE SVN repository in order to get
       the KDE identities with their name and e-mail address
    """
    maintainers = {}

    args = argparserutils.parse_args(DEPDIAGRAM_AVAILABLE)
    if args.accountsfile and os.path.exists(args.accountsfile):
        logging.debug("Found contributor identities file at %s", args.accountsfile)
        with codecs.open(args.accountsfile, 'r', encoding='utf8') as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) >= 3:
                    maintainers[parts[0]] = {
                        'name': ' '.join(parts[1:-1]),
                        'email': parts[-1]
                        }

    else:
        logging.debug("No contributor identities file found. Without the file, maintainer information will be incomplete. For generating KDE API documentation you can download the KDE accounts file from https://websvn.kde.org/*checkout*/trunk/kde-common/accounts and specify it with the --accountsfile argument.")


    return maintainers


def main():
    kde_copyright = '1996-' + str(datetime.date.today().year) + ' The KDE developers'
    get_maintainers = get_identities

    hlfunctions.do_it(maintainers_fct=get_maintainers,
                      copyright=kde_copyright)


if __name__ == "__main__":
    main()
